### ISSUE TITLE
Can't install from the repository

### ISSUE THREAD

**Issue by leorjorge** [biometry/bipartite#19]
Hi, I'm trying to install the dev version to be able to run modularity analyses (getting the same thing reported in #16 which seems to have been fixed in [c29d225](https://github.com/biometry/bipartite/commit/c29d225126e681a957279988be9df6589e0ae6ba) ). However, I'm getting the following error:
```
Error: Failed to install 'bipartite' from GitHub:
  input string 1 is invalid
In addition: Warning message:
In gsub("\n([^[:blank:]])", "\n \\1", val) :
  unable to translate 'c(person(given = "Carsten F.",
                    family = "Dormann",
                    role = c("aut", "cre"),
                    email = "carsten.dormann@biom.uni-freiburg.de",
                    comment = c(ORCID = "0000-0002-9835-1794")),
    ...' to a wide string
```

**Comment by cdormann** [comment]
This was due to non-UTF-8-characters in the contributors' names (e and a with accent); removed; should work now (does in test on windows)

**Comment by leorjorge** [comment]
Can confirm it works in Ubuntu as well. #16 is also fixed in this version. Thank you very much!
