### ISSUE TITLE
non-normalised C.score and checker are NOT the same

### ISSUE THREAD

**Issue by carzamora** [biometry/bipartite#2]
HI @cdormann,
I follow the example code of nested function and, in my result, non-normalised C.score and checker have not the same result, I just run the example in the function:

data(Safariland)
nested(Safariland, "ALL")
nested(Safariland, "ALL", rescale=TRUE)
# illustration that non-normalised C.score and checker are the same:
nested(Safariland, c("C.score", "checker"), normalise=FALSE)

This is my result:   
C.score   checker 
0.5616097 1.0227920 

thanks!

**Comment by cdormann** [comment]
Thanks! nested did not pass argument "normalised" correctly (typo in line 26, where it should be "normalise" in function call of "C.score".
Bug fixed and code committed.
