### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by DrMattG** [biometry/bipartite#20]
I get this error when I try and install via devtools::install_github("biometry/bipartite/bipartite").

I have tried devtools::install_github("biometry/bipartite/bipartite", build_vignettes = FALSE) as well but get the same error:

── R CMD build ──────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\matthew.grainger\AppData\Local\Temp\RtmpwZ1RRm\remotes1f5c4371896\biometry-bipartite-dfebfd3\bipartite/DESCRIPTION' (612ms)
─  preparing 'bipartite': (2.8s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
E  checking vignette meta-information (341ms)
   Output(s) listed in 'build/vignette.rds' but not in package:
     'inst/doc/Intro2bipartite.pdf'
   Run R CMD build without --no-build-vignettes to re-create
Error: Failed to install 'bipartite' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by cdormann** [comment]
fixed, should work now (the build-folder in the tar.gz was a left-over from a previous way of including the vignette; I forgot to remove it and have it re-generated during building); github-install now works on my computer, which previously reproduced the error.
