### ISSUE TITLE
Error from specieslevel function

### ISSUE THREAD

**Issue by MargaGF** [biometry/bipartite#22]
Hi all,

I am trying to run an analysis at the species level, but I am getting the error: 
Error in dimnames(x) <- dn : length of 'dimnames' [1] not equal to array extent

We could think there was something wrong with the structure of my data, however, I got the network level metrics with the same dataset. Also, my data are arranged in the same way as the Safariland data.  This is one of my datasets:

![dataset_example](https://github.com/user-attachments/assets/8554bd6a-9f2a-4460-80c9-a6bbac59b11c)

Do you have any idea of what could be wrong?

Cheers,

**Comment by MargaGF** [comment]
I was able to make it work by transposing the columns and rows :)

**Comment by cdormann** [comment]
I have no idea, why this wouldn't work. That you managed to get it working by transposing suggests (to me) that the data were not correctly formatted (e.g. rownames as a column, rather than attribute).
