### ISSUE TITLE
Bug in function "robustness"

### ISSUE THREAD

**Issue by hanlunliu** [biometry/bipartite#5]
Dear Carsten,

There is a bug in function "robustness" of bipartite 2.14. These are the first two lines of its code:
if (is(object, "bipartite")) 
        stop("This function cannot be meaningfully applied to objects of this class.")

It should be ' if (!is(object, "bipartite")) ' since function "second.extinct" returns object in class "bipartite". Please have a check.

Best,

Hanlun

**Comment by nefff1** [comment]
Yes, same problem here. Best, Felix

**Comment by cdormann** [comment]
You're absolutely right! This was a bug I introduced in the previous version when CRAN required the discontinuation of the "class" approach. I'll push a correction to github immediately. Thanks for letting me know!

**Comment by hanlunliu** [comment]
Thanks very much!
