### ISSUE TITLE
Error with H2_integer = F option of H2fun()

### ISSUE THREAD

**Issue by mxdub** [biometry/bipartite#7]
Hi,

When using the H2_integer = F option of H2fun() function, the function return an error indicating H2_max is not defined (at line 102). If I understand well,  I would suppose copying line 49 just after the line 32. It should make the job by defining H2_max.

Alternatively, the condition on line 102 may be kept only for cases where H2_integer = T since when it's not the case H2_max.improved = H2_max (assuming this later is defined...)
`H2_max <- ifelse(H2_integer && H2_max >= H2_max.improved, H2_max, H2_max.improved)`

Best whishes,

max

**Comment by mxdub** [comment]
Ok, I actually succeeded to create a pull request (using the second solution).

**Comment by cdormann** [comment]
I hope I merged your pull-request with the main branch. Many thanks!

**Comment by mxdub** [comment]
Actually, it looks you don't ^^
